//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megakorpa_servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbaProizvod
    {
        public int NarudzbaProizvodID { get; set; }
        public int NarudzbaID { get; set; }
        public int ProizvodID { get; set; }
        public int Kvantitet { get; set; }
        public decimal Cijena { get; set; }
    
        public virtual Narudzba Narudzba { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
