//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megakorpa_servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodjac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvodjac()
        {
            this.Proizvods = new HashSet<Proizvod>();
        }
    
        public int ProizvodjacID { get; set; }
        public string Naziv { get; set; }
        public string Telefon { get; set; }
        public string EMail { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> GradID { get; set; }
        public string WebStranica { get; set; }
        public string Napomene { get; set; }
    
        public virtual Grad Grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvod> Proizvods { get; set; }
    }
}
