//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megakorpa_servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposlenik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zaposlenik()
        {
            this.Narudzbas = new HashSet<Narudzba>();
        }
    
        public int ZaposlenikID { get; set; }
        public int RadnoMjestoID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string JMBG { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string Telefon { get; set; }
        public string EMail { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> GradID { get; set; }
        public string Napomene { get; set; }
    
        public virtual Grad Grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba> Narudzbas { get; set; }
        public virtual RadnoMjesto RadnoMjesto { get; set; }
    }
}
